Repository Mile-Writings/Mile-Client, pull requests merged in 2024-10, with the labels that each got.

#425 [ Refactor/#414 ] 페이지 이탈 커스텀훅 / react-router-dom 버전 업데이트
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/commons/Layout.tsx
  src/hooks/useBlockPageExit.ts
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/createGroup/CreateGroup.tsx
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/postPage/PostPage.tsx
  src/routers/Router.tsx
  yarn.lock
Labels: ♻️ Refactor, 서진, size/m

#419 [Refactor/#383] 공통 모달 리팩토링
  index.html
  package.json
  src/App.tsx
  src/assets/images/alertDelete.png
  src/assets/images/alertModify.png
  src/assets/svgs/alertDeletePng.svg
  src/assets/svgs/alertModifyPng.svg
  src/components/commons/Header.tsx
  src/components/commons/Layout.tsx
  src/components/commons/Modal.tsx
  src/components/commons/modal/DefaultModal.tsx
  src/components/commons/modal/FullModal.tsx
  src/components/commons/modal/constants.ts
  src/hooks/useBlockPageExit.ts
  src/hooks/useModal.ts
  src/pages/admin/components/EachTopic.tsx
  src/pages/admin/components/MemberManage.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/admin/constants/modal.ts
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/constants/modalContent.ts
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/constants/modalContent.ts
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/groupInvite/components/UserInfoInput.tsx
  src/pages/groupInvite/constants/modalContent.ts
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/constants/modalContent.ts
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/EditorContinueTempModal.tsx
  src/pages/postPage/components/EditorFlowModal.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/constants/modalContent.ts
  src/routers/Router.tsx
  yarn.lock
Labels: ♻️ Refactor, 서진, size/xl

#436 [design/#435] 글 모임 생성 페이지 가로 스크롤 추가
  src/pages/createGroup/components/CreateGroupInfo.tsx
Labels: 💄 Design, 서진, size/xs

#437 [ Design/#434 ] 푸터 변경사항 반영
  src/assets/svgs/iconNotion.svg
  src/assets/svgs/iconWalla.svg
  src/assets/svgs/index.tsx
  src/components/commons/Footer.tsx
  src/constants/footerLink.ts
Labels: 💄 Design, 서진, size/s

#438 [Fix/#428] 내 정보 get api 통합 + 링크미리보기 설정
  src/App.tsx
  src/assets/images/defaultSeaImage.png
  src/assets/images/image_area.png
  src/assets/images/mileLinkImg.png
  src/pages/admin/Admin.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/CuriousProfile.tsx
  src/pages/groupFeed/components/EditProfileModal.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/components/Comment.tsx
Labels: ✨ Feature, 다현, size/m

#442 [ Hotfix/#441 ] v5 머지 이후 qa (글모임생성 버튼 크기 / 페이지 이탈 모달 겹쳐서 뜨는 이슈 / 메타태그 수정)
  index.html
  src/App.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/createGroup/CreateGroup.tsx
Labels: 서진, size/s, 🔥 Hotfix

#446 [ Hotfix/#441 ] v5머지 이후 QA - 글모임생성 완료 후 그룹아이디 안 받아와지는 거 수정
  index.html
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/apis/postGroup.ts
  src/pages/createGroup/hooks/queries.ts
Labels: 서진, 🔥 Hotfix

#443 [ Hotfix/#441 ] v5 머지 이후 qa (글모임생성 버튼 크기 / 페이지 이탈 모달 겹쳐서 뜨는 이슈 / 메타태그 수정)
  index.html
  src/App.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/apis/postGroup.ts
  src/pages/createGroup/hooks/queries.ts
Labels: size/s

#448 [ Hotfix/#447 ] 글모임생성 변경된 api 반영 - accessToken 받아오는 로직 반영
  src/pages/createGroup/hooks/queries.ts
  src/pages/groupFeed/GroupFeed.tsx
  src/utils/apis/axios.ts
Labels: 서진, size/s, 🔥 Hotfix

#450 [ Hotfix/#449 ] 글 모임 초대 페이지 변경된 api 반영
  src/pages/groupInvite/apis/createGroupMemberJoin.ts
  src/pages/groupInvite/hooks/queries.ts
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
Labels: 서진, size/s, 🔥 Hotfix

#451 [ Hotfix/#447 ] hotfix main merge용 PR - 글모임생성 api 반영
  src/pages/createGroup/hooks/queries.ts
  src/pages/groupFeed/GroupFeed.tsx
  src/utils/apis/axios.ts
Labels: 서진, size/s, 🔥 Hotfix

#452 [ Hotfix/#449 ] hotfix main merge용 PR - 글모임가입 api 반영
  src/pages/groupInvite/apis/createGroupMemberJoin.ts
  src/pages/groupInvite/hooks/queries.ts
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
Labels: 서진, size/s, 🔥 Hotfix

#456 [fix/#455] 글감 데이터 자리 수정
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  yarn.lock
Labels: ⚒️ Fix, size/s

#458 [ hotfix ] 에디터 볼드, 기울기, 밑줄 globalStyle 반영
  src/styles/GlobalStyle.ts
Labels: size/xs

#445 [Refactor/#444] lottie 라이브러리 변경 및 build chunks 분리
  package.json
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/loading/Loading.tsx
  vite.config.ts
Labels: ♻️ Refactor, 다현, size/s
