Repository Mile-Writings/Mile-Client, pull requests merged in 2024-08, with the labels that each got.

#353 [Feat/#352] 댓글 뷰 변경사항 반영 & 캐러셀 화살표 disable
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/slick-theme.css
  src/pages/groupFeed/components/CuriousProfile.tsx
  src/pages/postDetail/components/CommentInputBox.tsx
  src/pages/postDetail/components/CommentItem.tsx
Labels: ✨ Feature, 다현, size/s

#370 [Feat/#369] 마지막 캐러셀 슬라이드 이미지 영역 QA 수정
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselContent.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/Manual.tsx
  src/utils/apis/axios.ts
Labels: ⚒️ Fix, 다은, size/m

#373 [Fix/#368] 각 페이지 줄바꿈 잘못 처리된 부분 수정
  src/components/commons/Button.tsx
  src/pages/main/constants/faqData.ts
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/checkPostAuth.ts
  src/pages/postPage/PostPage.tsx
Labels: ⚒️ Fix, 재훈, size/s

#381 [Fix/#380] 에디터 페이지 썸네일 추가 버튼 호버값, active값 수정, 썸네일 Border-radius 재적용
  src/assets/svgs/editorThuminputIcnUnactive.svg
  src/assets/svgs/index.tsx
  src/pages/postPage/components/ImageUpload.tsx
Labels: ⚒️ Fix, 서진, size/s

#379 [Fix/#376] qa checklist
  src/Router.tsx
  src/components/commons/ScrollToTop.tsx
  src/pages/admin/TopicAdmin.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/EditProfileModal.tsx
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postPage/PostPage.tsx
Labels: ⚒️ Fix, 다현, size/s

#375 [Fix/#374] QA 해결
  src/assets/svgs/adminMemberMaster.svg
  src/assets/svgs/defaultProfileIc.svg
  src/assets/svgs/index.tsx
  src/components/commons/Header.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/admin/components/AddEditTopicModal.tsx
  src/pages/admin/components/EachTopic.tsx
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/admin/components/MemberManage.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/admin/components/TopicAdmin.tsx
  src/pages/admin/constants/member.ts
  src/pages/admin/constants/modal.ts
  src/pages/createGroup/apis/getGroupNameValidation.ts
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupInvite/apis/createGroupMemberJoin.ts
  src/pages/groupInvite/components/GroupInfo.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/deletePost.ts
  src/pages/postDetail/apis/fetchCommentList.ts
  src/pages/postDetail/apis/fetchPostNestedComment.ts
  src/pages/postPage/apis/createPostContent.ts
  src/pages/postPage/apis/createTempSaveContent.ts
  src/pages/postPage/apis/editPutContent.ts
  src/pages/postPage/apis/fetchPresignedUrl.ts
  src/pages/postPage/apis/fetchTempSaveContent.ts
  src/pages/postPage/apis/fetchTopic.ts
  src/pages/postPage/apis/saveTempSaveContent.ts
  src/styles/theme.ts
Labels: ⚒️ Fix, 다은, size/l

#389 [ Refactor/#384 ] private router분리, login 페이지 처리,
  src/App.tsx
  src/components/commons/LogInOutBtn.tsx
  src/pages/admin/apis/deleteGroup.ts
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/admin/apis/fetchAdminGroupInfo.ts
  src/pages/admin/apis/fetchDeleteMember.ts
  src/pages/admin/apis/fetchInvitationLink.ts
  src/pages/admin/apis/fetchMemberInfo.ts
  src/pages/admin/apis/putAdminEditGroupInfo.ts
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/createGroup/apis/getGroupNameValidation.ts
  src/pages/createGroup/apis/postGroup.ts
  src/pages/error/Error.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/apis/fetchHeaderGroup.ts
  src/pages/groupFeed/hooks/queries.ts
  src/pages/groupInvite/apis/createGroupMemberJoin.ts
  src/pages/groupInvite/apis/fetchGroupInfo.ts
  src/pages/groupInvite/apis/fetchWriterNameConflict.ts
  src/pages/groupInvite/hooks/queries.ts
  src/pages/login/Login.tsx
  src/pages/login/apis/loginService.ts
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/checkPostAuth.ts
  src/pages/postDetail/apis/createPostCurious.ts
  src/pages/postDetail/apis/deleteCurious.ts
  src/pages/postDetail/apis/deletePost.ts
  src/pages/postDetail/apis/fetchCommentList.ts
  src/pages/postDetail/apis/fetchCuriousInfo.ts
  src/pages/postDetail/apis/fetchDeleteComment.ts
  src/pages/postDetail/apis/fetchDeleteNestedComment.ts
  src/pages/postDetail/apis/fetchPostComment.ts
  src/pages/postDetail/apis/fetchPostNestedComment.ts
  src/pages/postPage/apis/createPostContent.ts
  src/pages/postPage/apis/createTempSaveContent.ts
  src/pages/postPage/apis/deleteTempPost.ts
  src/pages/postPage/apis/editPutContent.ts
  src/pages/postPage/apis/fetchTempSaveContent.ts
  src/pages/postPage/apis/fetchTempSaveFlag.ts
  src/pages/postPage/apis/fetchTopic.ts
  src/pages/postPage/apis/saveTempSaveContent.ts
  src/routers/PrivateRoute.tsx
  src/routers/Router.tsx
  src/utils/apis/axios.ts
  src/utils/apis/login.ts
  src/utils/apis/refresh.ts
  src/utils/checkAuthenticate.ts
Labels: ✨ Feature, ♻️ Refactor, 재훈, size/l

#391 [Hotfix/#390] 게시글 수정하기로 들어왔을 경우 임시저장 글 존재 여부 api 쏘지 않도록 수정
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/hooks/queries.ts
Labels: 서진, size/xs, 🔥 Hotfix

#393 [Fix/#387] 권한관련 에러, 권한에 의한 접근 처리
  .eslintrc.json
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/hooks/queries.ts
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/postDetail/PostDetail.tsx
  src/utils/apis/axios.ts
Labels: ⚒️ Fix, 재훈, size/m, 🔥 Hotfix

#392 [Fix/#385] carousel bug
  src/assets/svgs/emptyCommentIc.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/noCommentIc.svg
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/slick-theme.css
  src/pages/postDetail/components/Comment.tsx
Labels: ⚒️ Fix, 다현, size/xl

#398 Hotfix/#397/change temp save api header
  src/pages/main/components/Introduction.tsx
  src/pages/postPage/apis/fetchTempSaveFlag.ts
Labels: size/xs, 🔥 Hotfix

#399 [ Hotfix/#397 ] 임시저장 api 인증된 axios로 요청하기]
  src/pages/main/components/Introduction.tsx
  src/pages/postPage/apis/fetchTempSaveFlag.ts
Labels: 재훈, size/xs, 🔥 Hotfix

#401 [ Hotfix/#400 ] 그룹초대, 글모임 상세 에러핸들링, 권한별 라우팅 수정
  src/pages/groupFeed/hooks/queries.ts
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/groupInvite/apis/fetchGroupInfo.ts
  src/pages/groupInvite/components/GroupInfo.tsx
  src/pages/groupInvite/hooks/queries.ts
  src/pages/postDetail/PostDetail.tsx
  src/utils/apis/axios.ts
Labels: 재훈, size/s, 🔥 Hotfix

#396 [Hotfix/#394] replace alt with default Image
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselContent.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/skeletons/SkeletonComponent.tsx
  src/pages/postDetail/PostDetail.tsx
  src/utils/replaceDefaultImg.ts
Labels: 다은, size/s, 🔥 Hotfix

#403 [Hotfix/#394] replace img with default value
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselContent.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/skeletons/SkeletonComponent.tsx
  src/pages/postDetail/PostDetail.tsx
  src/utils/replaceDefaultImg.ts
Labels: 다은, size/s, 🔥 Hotfix

#407 [hotfix/#404] 캐러셀 본문과 이미지 간 gap 추가
  src/pages/main/components/CarouselContent.tsx
Labels: size/xs, 🔥 Hotfix

#410 [Hotfix/#409] 글모임 초대페이지 - 존재하지 않는 글모임 40010,40014에 대한 에러처리
  src/pages/groupInvite/GroupInvite.tsx
Labels: 재훈, size/s, 🔥 Hotfix

#411 [ Hotfix/#409 ] group invite400error handling (to develop)
  src/pages/groupInvite/GroupInvite.tsx
Labels: 재훈, 🔥 Hotfix

#412 [ Hotfix/#409 ] group 초대페이지 에러 핸들링 수정 , 로그인 페이지에서 이전페이지 라우팅하는 기능 추가
  src/pages/groupInvite/GroupInvite.tsx
  src/utils/apis/axios.ts
Labels: 재훈, size/s, 🔥 Hotfix

#413 [ Hotfix/#409] group invite error handling (to main)
  src/pages/groupInvite/GroupInvite.tsx
  src/utils/apis/axios.ts
Labels: 재훈, size/s, 🔥 Hotfix
