Repository Mile-Writings/Mile-Client, pull requests merged in 2024-06, with the labels that each got.

#331 [Feat/#329] 무한스크롤
  src/pages/admin/components/MemberManage.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/hooks/queries.ts
Labels: ✨ Feature, 다현, size/m

#339 [Fix/#338] 초대 링크 변경
  src/pages/admin/Admin.tsx
  src/pages/createGroupSuccess/CreateGroupSuccess.tsx
  src/utils/copyLink.ts
Labels: ⚒️ Fix, 다은, size/s

#343 [Feat/#342] 초대링크 로그아웃일 때 로그인 페이지로 라우팅
  src/pages/groupInvite/GroupInvite.tsx
Labels: ✨ Feature, 다은, size/xs

#345 [fix/#336] 캐러셀 새로고침 방지
  src/pages/groupFeed/carousel/Carousel.tsx
Labels: ⚒️ Fix, 다현, size/xs

#344 [Refactor/#323] 글모임 생성 리팩토링
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/commons/Header.tsx
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupTopicModal.tsx
  src/pages/createGroup/constants/topicLenth.ts
  src/pages/createGroup/hooks/queries.ts
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  yarn.lock
Labels: ♻️ Refactor, 재훈, size/m

#346 main merge v4
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/commons/Header.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/components/MemberManage.tsx
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupTopicModal.tsx
  src/pages/createGroup/constants/topicLenth.ts
  src/pages/createGroup/hooks/queries.ts
  src/pages/createGroupSuccess/CreateGroupSuccess.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/TipTap.tsx
  src/pages/postPage/components/tiptap.css
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/utils/copyLink.ts
  yarn.lock
Labels: size/xl

#348 loading 경로 수정
  src/pages/groupFeed/carousel/EachArticle.tsx
Labels: size/xs

#349 [ hotfix ] 로딩 스피너 버셀 배포 에러 경로 import로 수정
  src/pages/groupFeed/carousel/EachArticle.tsx
Labels: size/xs

#350 hotfix: login redirect 리퀘스트 바디 수정
  src/components/commons/Header.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/login/apis/loginService.ts
Labels: size/xs

#351 hotfix : 로그인 redirect uri 리퀘스트헤더 변경
  src/components/commons/Header.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/login/apis/loginService.ts
Labels: size/xs

#358 [Feat/#355] 공개모임 여부 api 연결
  src/mocks/handler.ts
  src/pages/admin/AddEditTopicModal.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/hooks/queries.ts
Labels: ✨ Feature, 다현, size/s

#359 [Feat] 글 모임 장인 경우 멤버 삭제 불가
  src/pages/admin/apis/fetchMemberInfo.ts
  src/pages/admin/components/MemberManage.tsx
Labels: ✨ Feature, 다은, size/s

#360 [Feat] 관리자 페이지 모임 버튼
  src/assets/svgs/adminHomeIcn.svg
  src/assets/svgs/index.tsx
  src/components/commons/LogInOutBtn.tsx
  src/pages/admin/Admin.tsx
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
Labels: ✨ Feature, 다은, size/s

#362 [Feat] 글 상세 페이지 디테일 정보 추가
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchPostDetail.ts
Labels: ✨ Feature, 다은, size/s

#363 [ Feat/#354 ] 관리자 글모임 정보 수정 페이지
  src/Router.tsx
  src/constants/defaultImgUrl.ts
  src/hooks/useGroupImage.ts
  src/pages/admin/EditGroupInfo.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/apis/fetchAdminGroupInfo.ts
  src/pages/admin/apis/putAdminEditGroupInfo.ts
  src/pages/admin/hooks/queries.ts
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/apis/getGroupNameValidation.ts
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupLeaderInfo.tsx
  src/pages/createGroup/hooks/queries.ts
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/hooks/useCustomBack.ts
  src/pages/postPage/components/ImageUpload.tsx
  src/utils/s3UrlParsing.ts
Labels: ✨ Feature, 재훈, size/l

#365 [Feat/#364] 글모임 삭제 기능 구현
  src/App.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/apis/deleteGroup.ts
  src/pages/admin/hooks/queries.ts
  src/pages/createGroup/CreateGroup.tsx
  src/pages/loading/Loading.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/hooks/useCustomBack.ts
Labels: ✨ Feature, 재훈, size/m

#366 Release 2
  src/App.tsx
  src/Router.tsx
  src/assets/svgs/adminHomeIcn.svg
  src/assets/svgs/index.tsx
  src/components/commons/LogInOutBtn.tsx
  src/constants/defaultImgUrl.ts
  src/hooks/useGroupImage.ts
  src/mocks/handler.ts
  src/pages/admin/AddEditTopicModal.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/EditGroupInfo.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/apis/deleteGroup.ts
  src/pages/admin/apis/fetchAdminGroupInfo.ts
  src/pages/admin/apis/fetchMemberInfo.ts
  src/pages/admin/apis/putAdminEditGroupInfo.ts
  src/pages/admin/components/MemberManage.tsx
  src/pages/admin/hooks/queries.ts
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/apis/getGroupNameValidation.ts
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupLeaderInfo.tsx
  src/pages/createGroup/hooks/queries.ts
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/loading/Loading.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchPostDetail.ts
  src/pages/postDetail/hooks/useCustomBack.ts
  src/pages/postPage/components/ImageUpload.tsx
  src/utils/s3UrlParsing.ts
Labels: size/xl, Release
