Repository Mile-Writings/Mile-Client, pull requests merged in 2024-12, with the labels that each got.

#485 [Feat/#473] admin 글감 반응형 구현
  .gitignore
  src/components/commons/inputModal/InputModal.tsx
  src/constants/modal.ts
  src/pages/admin/Admin.tsx
  src/pages/admin/components/EachTopic.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/admin/components/TopicAdmin.tsx
  src/pages/admin/components/navbar/DesktopNav.tsx
  src/pages/admin/components/navbar/MobileNav.tsx
  src/pages/admin/hooks/useMenu.ts
  src/pages/admin/types/menu.ts
  src/utils/PageNumber.tsx
Labels: ✨ Feature, size/l

#483 [ Feat/#481] 그룹 생성페이지 플로우 반응형 전환
  src/components/commons/Header.tsx
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/admin/hooks/queries.ts
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupLeaderInfo.tsx
  src/pages/createGroup/constants/inputInfoMsg.ts
  src/pages/createGroupSuccess/CreateGroupSuccess.tsx
Labels: ✨ Feature, 💄 Design, 재훈, size/m

#486 [Feat/#482] 반응형 헤더 구현
  src/assets/svgs/hamburgerIcon.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/linkIcon.svg
  src/components/commons/Header.tsx
  src/components/commons/HeaderButton.tsx
  src/components/commons/LogInOutBtn.tsx
  src/components/commons/MyMobileSidebar.tsx
  src/pages/admin/Admin.tsx
  src/pages/createGroup/CreateGroup.tsx
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
Labels: ✨ Feature, 다현, size/l

#493 [Feat/#473] admin 멤버 관리 반응형 구현
  src/pages/admin/Admin.tsx
  src/pages/admin/components/EachTopic.tsx
  src/pages/admin/components/MemberItem.tsx
  src/pages/admin/components/MemberManage.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/admin/components/TopicAdmin.tsx
Labels: ✨ Feature, 💄 Design, 다은, size/m

#491 [Feat/#488] 모임초대페이지 반응형
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/groupInvite/components/GroupInfo.tsx
  src/pages/groupInvite/components/Title.tsx
  src/pages/groupInvite/components/UserInfoInput.tsx
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 서진, size/m

#496 [Feat/#489] 글 상세페이지 반응형 구현
  src/assets/svgs/divideDot.svg
  src/assets/svgs/index.tsx
  src/components/commons/Button.tsx
  src/components/commons/Header.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentInputBox.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 서진, size/m

#498 [Feat/#479] 에디터 뷰 모바일 반응형 구현
  src/assets/svgs/bin.svg
  src/assets/svgs/closeIcn.svg
  src/assets/svgs/editorSVG.tsx
  src/components/commons/Spacing.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/TipTap.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/components/mobile/MobileHeader.tsx
  src/pages/postPage/components/mobile/MobileToolbarFontColor.tsx
  src/pages/postPage/components/tiptap.css
Labels: ✨ Feature, 서진, size/xl

#495 [ Refactor/#484 ] 이미지 최적화 image to webp
  src/constants/supportedImageType.ts
  src/hooks/useImageUpload.ts
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/createGroup/CreateGroup.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/directUploadS3.ts
  src/pages/postPage/components/ImageUpload.tsx
  src/types/global.d.ts
  src/types/imageUploadType.ts
  src/utils/convertImageToWebP.ts
  src/utils/handleImageUpload.ts
  src/utils/isSupportedImageType.ts
Labels: ♻️ Refactor, 재훈, size/m

#501 [Feat/#492] 모임페이지 반응형
  src/assets/svgs/groupCardThumnailImg.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/popularMobile.svg
  src/components/commons/Button.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/CarouselContainer.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/carousel/slick-theme.css
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/CuriousProfile.tsx
  src/pages/groupFeed/components/GroupCuriousTitle.tsx
  src/pages/groupFeed/components/GroupInfoBox.tsx
  src/pages/groupFeed/components/GroupMobileInfo.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/main/styles/slick.css
Labels: 💄 Design, 다현, size/l

#497 [ Feat/#494 ] Admin - 글모임 정보 수정 페이지 반응형 웹으로 구현
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
Labels: 💄 Design, 재훈, size/m

#504 [Feat/#503] 로그인 반응형 뷰 구현
  src/pages/login/Login.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 다은, size/s

#505 [ Feat/#500 ] meta tag og data dynamic 생성
  .babelrc
  .gitignore
  index.html
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/postDetail/PostDetail.tsx
  src/utils/apis/axios.ts
  src/utils/apis/getAllPost.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 재훈, size/m

#506 [ Feat/#500 ] pupetter 제거 후 Helmet 사용으로 OG적용
  package.json
  src/pages/postDetail/PostDetail.tsx
  src/utils/apis/getAllPost.ts
  vite.config.ts
Labels: size/m

#508 [fix/#507] 햄버거바 에러
  src/components/commons/Header.tsx
  src/components/commons/MyMobileSidebar.tsx
Labels: ⚒️ Fix, 다현, size/s

#509 [ Feat/#500 ] 동정 OG image 배포 에러 해결 ( 버전 맞추기, port 변경, legacy 버전 이슈 해결로 빌드 성공_
  package.json
  src/utils/crawler.ts
  vite.config.ts
  yarn.lock
Labels: ⚒️ Fix, 재훈, size/m

#510 [ Feat/#500 ] dynamic og Meta tag 추가하기
  src/utils/allPostParsing.ts
  src/utils/getPostDetailParsingMetatg.ts
  vite.config.ts
Labels: ✨ Feature, 재훈, size/m

#511 [ Feat/#500 ] dynamic og meta tag prerender 성공
  package.json
  vite.config.ts
Labels: ⚒️ Fix, 재훈, size/s

#512 [ Feat/#500 ] dynamic og image - vercel path routing setting 수정
  vercel.json
Labels: ⚒️ Fix, 재훈, size/xs

#513 feat: 일반 페이지 og태그 원복
  index.html
Labels: ✨ Feature, 재훈, size/xs

#514 [ Feat/#500 ] meta tag 중복 삭제 및 api url env활용
  src/utils/allPostParsing.ts
  vite.config.ts
Labels: ♻️ Refactor, 재훈, size/s

#515 fix: og tag url env 수정
  vite.config.ts
Labels: size/xs

#516 [ Feat/#500 ] 주석제거 및 og:url env로 추가
  vite.config.ts
Labels: ⚒️ Fix, 재훈, size/s

#517 [ Feat/#500 ] prerender 파이프라인 구축 후 글 페이지에 대한 dynamic og meta tag 추가
  public/mockServiceWorker.js
  public/vite.svg
  src/pages/postDetail/PostDetail.tsx
  src/utils/crawler.ts
  src/utils/generateDynamicRoute.ts
  vite.config.ts
  yarn.lock
Labels: size/m
