Repository Mile-Writings/Mile-Client, pull requests merged in 2024-09, with the labels that each got.

#422 [design/#421] 글모임생성페이지 마진값 이상한 거 수정
  src/pages/createGroupSuccess/CreateGroupSuccess.tsx
Labels: 💄 Design, 서진, size/xs

#417 [Feat/#416] 400handling
  src/constants/commentErrorMessage.ts
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/admin/hooks/queries.ts
  src/pages/createGroup/hooks/queries.ts
  src/pages/groupInvite/hooks/queries.ts
  src/pages/postDetail/hooks/queries.ts
  src/pages/postPage/hooks/queries.ts
Labels: size/m

#427 [Feat/#426] 500대 에러 처리
  src/utils/apis/axios.ts
Labels: ✨ Feature, 다은, size/xs

#431 [ Fix/#430 ] editor페이지 toolbar sticky 적용
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/TipTap.tsx
Labels: ⚒️ Fix, size/s

#424 [ Refactor/#423 ] group page query key 리팩토링
  src/Router.tsx
  src/mocks/handler.ts
  src/pages/admin/hooks/queries.ts
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/groupInvite/components/GroupInfo.tsx
Labels: ♻️ Refactor, 재훈, size/m
