Repository Mile-Writings/Mile-Client, pull requests merged in 2024-02, with the labels that each got.

#218 [Fix/#217] 폴더명 변경
  src/Router.tsx
  src/pages/error/Error.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/loading/Loading.tsx
  src/pages/login/RedirectLogin.tsx
  src/pages/postDetail/PostDetail.tsx
Labels: ⚒️ Fix, 다은, size/s

#216 [Fix/#215] skeleton UI 수정
  src/pages/login/hooks/useLoginService.ts
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/CarouselPage.tsx
  src/pages/main/components/CarouselSkeleton.tsx
  src/pages/main/components/CarouselSkeletonPage.tsx
  src/pages/main/components/skeletons/Skeleton.tsx
  src/pages/main/components/skeletons/SkeletonComponent.tsx
  src/pages/main/constants/keyword.ts
  src/pages/main/hooks/queries.ts
  src/pages/main/types/groupContent.ts
  src/pages/postDetail/apis/fetchPostComment.ts
  src/pages/postDetail/components/Comment.tsx
  src/utils/apis/getGroupContentApi.ts
Labels: ⚒️ Fix, 다은, size/m

#220 [Feat/#219] 로그인 페이지 에러 핸들링
  src/pages/login/Login.tsx
  src/pages/main/components/Carousel.tsx
Labels: ✨ Feature, ⚒️ Fix, 다은, size/xs

#225 [Refactor/#213] 에디터 뷰 임시저장, 수정, 최초저장 플로우 리팩토링
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/fetchTempSaveFlag.ts
  src/pages/postPage/apis/fetchTopic.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/EditorToolBar.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/Topic.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/components/TopicType.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/constants/editorDefaultImg.ts
  src/pages/postPage/constants/temporarySaveData.ts
  src/pages/postPage/constants/topicConstants.ts
  src/pages/postPage/hooks/queries.ts
  src/pages/postPage/utils/s3UrlParsing.ts
Labels: ♻️ Refactor, 서진, size/l

#231 [Refactor/#226] 에디터 라이브러리 변경
  package.json
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/TipTap.tsx
  src/pages/postPage/components/tiptap.css
  src/pages/postPage/utils/fontSize.ts
  src/pages/postPage/utils/fontWeight.ts
  src/pages/postPage/utils/lineHeight.ts
  yarn.lock
Labels: ♻️ Refactor, 서진, size/xl

#228 Fix/#193/qa fix
  src/Router.tsx
  src/pages/error/Error.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/loading/Loading.tsx
  src/pages/login/RedirectLogin.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/Comment.tsx
Labels: ⚒️ Fix, 재훈, size/s
