Repository Mile-Writings/Mile-Client, pull requests merged in 2024-04, with the labels that each got.

#270 [Feat/#267] 관리자페이지 글감설정 뷰 & 공통 페이지네이션 & msw 적용
  package.json
  public/mockServiceWorker.js
  src/assets/svgs/arrowLeft.svg
  src/assets/svgs/arrowRight.svg
  src/assets/svgs/btn_makegroup.svg
  src/assets/svgs/deleteBtn.svg
  src/assets/svgs/editBtn.svg
  src/assets/svgs/index.tsx
  src/components/commons/Button.tsx
  src/components/commons/Pagenation.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handler.ts
  src/pages/admin/EachTopic.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/TopicAdmin.tsx
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/admin/hooks/queries.ts
  src/utils/PageNumber.tsx
  src/utils/countPage.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feature, 다현, size/xl

#272 [Fix/#265] 메인페이지 수정사항 반영
  src/assets/svgs/index.tsx
  src/assets/svgs/mainGraphicLogo.svg
  src/assets/svgs/mainIcnArrowBlack.svg
  src/assets/svgs/mainOnBoarding.svg
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselContent.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/Manual.tsx
  src/pages/main/constants/faqData.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, ⚒️ Fix, 다은, size/m

#274 [Feat/#269] 에디터 뷰 모달
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/createPostContent.ts
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/EditorContinueTempModal.tsx
  src/pages/postPage/components/EditorFlowModal.tsx
  src/pages/postPage/components/GetTempSaveModal.tsx
  src/pages/postPage/components/Icons.tsx
  src/pages/postPage/components/editor.css
  src/pages/postPage/hooks/queries.ts
  src/pages/postPage/utils/modalPreventScroll.ts
Labels: ✨ Feature, 서진, size/xl

#280 [Feat/#279] 모임 상세페이지 대댓글 뷰
  src/assets/svgs/arrow_top_left.svg
  src/assets/svgs/check.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/mode_comment.svg
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentInputBox.tsx
  src/pages/postDetail/components/CommentItem.tsx
Labels: ✨ Feature, 다현, size/m

#282 [Fix/#278] 공통 모달 버그 수정
  src/components/commons/Modal.tsx
  src/hooks/useModal.tsx
Labels: ⚒️ Fix, 다은, size/m

#285 [ feat/#273 ] 관리자 페이지 글감 설정 모달 구현 & 사이드헤더 ui 변경사항 반영
  src/components/commons/Modal.tsx
  src/mocks/handler.ts
  src/pages/admin/AddEditTopicModal.tsx
  src/pages/admin/EachTopic.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/admin/hooks/queries.ts
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 다현, size/l

#286 [Fix/#278] 공통 모달 스크롤 방지 함수 적용
  src/components/commons/Modal.tsx
Labels: ⚒️ Fix, 다은, size/xs

#301 [Feat/#277] 글 모임 초대 페이지 api 연결
  src/Router.tsx
  src/assets/svgs/index.tsx
  src/assets/svgs/joinCongratulationPng.svg
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/groupInvite/apis/createGroupMemberJoin.ts
  src/pages/groupInvite/apis/fetchGroupInfo.ts
  src/pages/groupInvite/apis/fetchWriterNameConflict.ts
  src/pages/groupInvite/components/GroupInfo.tsx
  src/pages/groupInvite/components/UserInfoInput.tsx
  src/pages/groupInvite/hooks/queries.ts
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
  src/pages/postPage/apis/createPostContent.ts
Labels: ✨ Feature, 서진, size/l

#304 [Feat/#297] 에디터 뷰 변경된 api 연결
  package.json
  src/assets/svgs/alertCautionPng.svg
  src/assets/svgs/alertStoragePng.svg
  src/assets/svgs/alertUploadPng.svg
  src/assets/svgs/editorErrorSvg.svg
  src/assets/svgs/editorSVG.tsx
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/apis/fetchCommentList.ts
  src/pages/postDetail/apis/fetchCuriousInfo.ts
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/createPostContent.ts
  src/pages/postPage/apis/deleteTempPost.ts
  src/pages/postPage/apis/editPutContent.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/EditorContinueTempModal.tsx
  src/pages/postPage/components/EditorFlowModal.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/TipTap.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/constants/editorDefaultImg.ts
  src/pages/postPage/hooks/queries.ts
  yarn.lock
Labels: ✨ Feature, 서진, size/m

#298 [Feat/#293] 초대 링크 api GET
  src/pages/admin/Admin.tsx
  src/pages/admin/apis/fetchInvitationLink.ts
  src/pages/admin/hooks/queries.ts
  src/utils/apis/axios.ts
Labels: ✨ Feature, 다은, size/s

#299 [Feat/#266] 멤버 관리 페이지 뷰 & api
  src/assets/images/adminImgProfile.png
  src/assets/svgs/adminEmptyMember.svg
  src/assets/svgs/adminProfileIc.svg
  src/assets/svgs/index.tsx
  src/components/commons/Pagenation.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/apis/fetchDeleteMember.ts
  src/pages/admin/apis/fetchMemberInfo.ts
  src/pages/admin/components/MemberManage.tsx
  src/pages/admin/constants/member.ts
  src/pages/admin/hooks/queries.ts
  src/utils/apis/axios.ts
Labels: ✨ Feature, 다은, size/m

#300 [Fix/#265] 메인 페이지 수정 사항 반영
  src/App.tsx
  src/assets/svgs/index.tsx
  src/assets/svgs/mainGraphicGradation.svg
  src/assets/svgs/mainManualCurious.svg
  src/assets/svgs/mainManualJoin.svg
  src/assets/svgs/mainManualLook.svg
  src/assets/svgs/mainManualMake.svg
  src/assets/svgs/mainManualShare.svg
  src/assets/svgs/mainManualWrite.svg
  src/pages/main/components/DailyKeyword.tsx
  src/pages/main/components/Introduction.tsx
  src/utils/apis/axios.ts
Labels: ⚒️ Fix, 다은, size/m

#302 [Feat/#292] 헤더 드롭다운 API GET
  src/pages/groupFeed/apis/fetchHeaderGroup.ts
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/constants/myGroupName.ts
  src/pages/groupFeed/hooks/queries.ts
Labels: ✨ Feature, 다은, size/m

#294 [Feat/#291] [DELETE] 관리자페이지 글감 삭제
  src/pages/admin/AddEditTopicModal.tsx
  src/pages/admin/EachTopic.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/admin/TopicAdmin.tsx
  src/pages/admin/apis/fetchAdminData.ts
  src/pages/admin/hooks/queries.ts
Labels: ✨ Feature, 다현, size/m

#305 [Feat/#277] 글 모임 초대페이지 API 추가
  src/components/commons/Modal.tsx
  src/pages/groupInvite/GroupInvite.tsx
  src/pages/groupInvite/apis/createGroupMemberJoin.ts
  src/pages/groupInvite/components/UserInfoInput.tsx
  src/pages/groupInvite/hooks/queries.ts
Labels: ✨ Feature, 서진, size/s
