Repository Mile-Writings/Mile-Client, pull requests merged in 2024-11, with the labels that each got.

#464 [design/#463] 글감태그 정렬 수정
  src/pages/admin/components/EachTopic.tsx
Labels: 💄 Design, 서진, size/xs

#466 [design/#465] 글상세페이지 숫자, 영문, 특수문자 줄바꿈 안됨 이슈
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/postDetail/PostDetail.tsx
Labels: 💄 Design, 서진, size/xs

#470 [ Feat/#468 ] 글 수정시 글조회 api 연결
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/fetchEditContent.ts
  src/pages/postPage/apis/fetchEditPostContent.ts
  src/pages/postPage/hooks/queries.ts
  src/routers/Router.tsx
Labels: ✨ Feature, 서진, size/s

#469 [Refactor/#461] 큰 일러 webp로 교체 및 대체이미지 설정
  src/assets/images/errorIlust.png
  src/assets/webps/creategroup.webp
  src/assets/webps/error.webp
  src/assets/webps/joincongratulation.webp
  src/assets/webps/login.webp
  src/assets/webps/mainmanualcurious.webp
  src/assets/webps/mainmanualjoin.webp
  src/assets/webps/mainmanuallook.webp
  src/assets/webps/mainmanualmake.webp
  src/assets/webps/mainmanualshare.webp
  src/assets/webps/mainmanualwrite.webp
  src/assets/webps/mainonboarding.webp
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/error/Error.tsx
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
  src/pages/login/Login.tsx
  src/pages/main/components/Manual.tsx
  src/pages/main/components/OnBoarding.tsx
  src/pages/main/constants/mainManualImgURL.ts
  vite.config.ts
Labels: ✨ Feature, 다현, size/s

#475 [Feat/#474] responsive basic setting & main page 임시 responsive 뷰 적용
  .stylelintrc
  package.json
  src/App.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Responsive/Responsive.tsx
  src/components/commons/Responsive/ResponsiveProvider.tsx
  src/components/commons/Responsive/context.ts
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselContent.tsx
  src/pages/main/components/DailyKeyword.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/Manual.tsx
  src/pages/main/components/OnBoarding.tsx
  src/pages/main/components/skeletons/CarouselSkeleton.tsx
  src/pages/main/styles/slick-theme.css
  src/pages/main/styles/slick.css
  src/styles/mediaQuery.ts
  yarn.lock
Labels: ♻️ Refactor, size/l
