Repository Mile-Writings/Mile-Client, pull requests merged in 2024-03, with the labels that each got.

#238 [Refactor/#237] 에디터 툴바 글자 색상 변경 뷰 커스텀
  src/assets/svgs/index.tsx
  src/pages/postPage/components/TipTap.tsx
Labels: ♻️ Refactor, 서진, size/m

#240 [Refactor/#239] 에디터 툴바 글자 배경 색상 변경 뷰 커스텀
  src/assets/svgs/index.tsx
  src/pages/postPage/components/TipTap.tsx
Labels: ♻️ Refactor, 서진, size/m

#243 [Fix/#242] login routing to before
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/login/RedirectLogin.tsx
  src/pages/login/hooks/useLoginService.ts
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/postDetail/PostDetail.tsx
Labels: ⚒️ Fix, 재훈, size/s

#245 [Feat/#103] 메인페이지 리액트 쿼리 적용
  src/pages/login/hooks/useLoginService.ts
  src/pages/main/Main.tsx
  src/pages/main/apis/getGroupContentApi.ts
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/CarouselPage.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/GroupCarouselTitle.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/Ruler.tsx
  src/pages/main/components/skeletons/SkeletonComponent.tsx
  src/pages/main/hooks/queries.ts
  src/pages/main/types/recommendTopic.ts
Labels: ✨ Feature, 다은, size/m

#247 [ refactor/#241 ] 에디터 툴바 나머지 커스텀
  src/assets/svgs/editorBoldSvg.svg
  src/assets/svgs/editorBoldSvgActive.svg
  src/assets/svgs/editorBoldSvgActivehover.svg
  src/assets/svgs/editorBoldSvgEnable.svg
  src/assets/svgs/editorBoldSvgHover.svg
  src/assets/svgs/editorBulletSvg.svg
  src/assets/svgs/editorCenterSvg.svg
  src/assets/svgs/editorHorizonSvg.svg
  src/assets/svgs/editorItalicSvg.svg
  src/assets/svgs/editorLeftSvg.svg
  src/assets/svgs/editorLineSvg.svg
  src/assets/svgs/editorNumberSvg.svg
  src/assets/svgs/editorQuoteSvg.svg
  src/assets/svgs/editorSVG.tsx
  src/assets/svgs/editorStrikeSvg.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/leftTest.svg
  src/pages/postPage/components/TipTap.tsx
Labels: ♻️ Refactor, 서진, size/m

#250 [ Fix/#222/qa ] 모임페이지 qa
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ♻️ Refactor, 다현, size/s

#263 [Feat/#260] 관리자 페이지 공통 레이아웃 구현
  src/Router.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/RenderAdminContent.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/main/hooks/queries.ts
  src/pages/postPage/PostPage.tsx
Labels: ✨ Feature, 다현, size/m

#258 [Refactor/#257] 메인 컴포넌트 리팩토링
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselContent.tsx
  src/pages/main/components/CuriousGroup.tsx
  src/pages/main/components/DailyKeyword.tsx
  src/pages/main/components/FaqTitle.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/OnBoarding.tsx
  src/pages/main/components/skeletons/CarouselSkeleton.tsx
  src/pages/main/components/skeletons/SkeletonComponent.tsx
Labels: ♻️ Refactor, 다은, size/m

#261 [Feat/#259] 헤더 드롭다운 구현 & 스타일 수정사항 반영
  src/assets/svgs/index.tsx
  src/assets/svgs/mainMakeGroupBtnEnable.svg
  src/assets/svgs/mainMakeGroupPlusBtn.svg
  src/components/commons/Header.tsx
  src/components/commons/LogInOutBtn.tsx
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/constants/myGroupName.ts
Labels: ✨ Feature, 다은, size/m

#264 [Feat/#262] 공통 모달 구현
  src/components/commons/Modal.tsx
Labels: ✨ Feature, 다은, size/m
