Repository Mile-Writings/Mile-Client, pull requests merged in 2024-01, with the labels that each got.

#4 [Init/#3] 프로젝트 초기세팅
  .eslintrc.json
  .gitignore
  .prettierrc
  MILE-Writings/.prettierrc.json
  MILE-Writings/README.md
  MILE-Writings/src/App.css
  MILE-Writings/src/App.tsx
  MILE-Writings/src/assets/react.svg
  MILE-Writings/src/index.css
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 🪡 Init, 재훈

#16 [Init/#15] emotion settings
  .babelrc
  package.json
  src/App.tsx
  src/main.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🪡 Init, 재훈

#18 [ Feat/#17] svg to react component
  package.json
  src/App.tsx
  src/assets/svgs/Rectangle 17.svg
  src/assets/svgs/index.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 다현

#28 [Init/#26] permission 생성 후 최초 PR에 사이즈 라벨 생기는지 확인
  .github/workflows/labeler.yml
Labels: 🪡 Init, 서진, size/s

#23 [Feat/#19] emotion lint 정렬자동화 수정
  .stylelintrc
  .stylelintrc.json
  src/App.tsx
Labels: ⚒️ Fix, 다현

#29 [Init/#20] theme, GlobalStyle 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/styles/GlobalStyle.tsx
  src/styles/emotion.d.ts
  src/styles/fonts/Pretendard-Black.woff
  src/styles/fonts/Pretendard-Bold.woff
  src/styles/fonts/Pretendard-ExtraBold.woff
  src/styles/fonts/Pretendard-ExtraLight.woff
  src/styles/fonts/Pretendard-Light.woff
  src/styles/fonts/Pretendard-Medium.woff
  src/styles/fonts/Pretendard-Regular.woff
  src/styles/fonts/Pretendard-SemiBold.woff
  src/styles/fonts/Pretendard-Thin.woff
  src/styles/theme.ts
  yarn.lock
Labels: 🪡 Init, 다은, size/l

#31 [Fix/#30]stylelint conflict
  .stylelintrc
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  yarn.lock
Labels: ⚒️ Fix, 재훈, size/l

#40 [ Feat/#37 ] router & pretendard 폰트 재적용
  index.html
  src/App.tsx
  src/Router.tsx
  src/assets/images/kakao_login_medium_wide.png
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/login/Login.tsx
  src/pages/main/Main.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postEditor/PostEditor.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 재훈, size/m

#38 [Feat/#34] footer 및 spacing component 구현
  src/assets/svgs/footerInstaSvg.svg
  src/assets/svgs/footerKakaoSvg.svg
  src/assets/svgs/footerLogoSvg.svg
  src/assets/svgs/footerMailSvg.svg
  src/assets/svgs/index.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Spacing.tsx
Labels: ✨ Feature, 다현, size/m

#41 [Feat/#33] 버튼 공통 컴포넌트 구현
  src/components/common/Button.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 서진, size/m

#45 [Feat/#22]kakao social login
  .gitignore
  package.json
  src/App.tsx
  src/Router.tsx
  src/pages/login/Login.tsx
  src/pages/login/RedirectLogin.tsx
  src/styles/fonts/Pretendard-Black.woff
  src/styles/fonts/Pretendard-Bold.woff
  src/styles/fonts/Pretendard-ExtraBold.woff
  src/styles/fonts/Pretendard-ExtraLight.woff
  src/styles/fonts/Pretendard-Light.woff
  src/styles/fonts/Pretendard-Medium.woff
  src/styles/fonts/Pretendard-Regular.woff
  src/styles/fonts/Pretendard-SemiBold.woff
  src/styles/fonts/Pretendard-Thin.woff
  src/utils/apis/axios.ts
  src/utils/apis/login.ts
  yarn.lock
Labels: ✨ Feature, 재훈, size/m

#42 [Feat/#39] 헤더 구현
  src/assets/svgs/headerLogoSvg.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/mainMakeGroupBtnEnable.svg
  src/assets/svgs/mainMakeGroupBtnHover.svg
  src/components/commons/Button.tsx
  src/components/commons/Header.tsx
  src/components/commons/LogInOutBtn.tsx
  src/pages/groupFeed/MakeGroupBtn.tsx
  src/pages/groupFeed/MyGroupBtn.tsx
  src/styles/emotion.d.ts
Labels: ✨ Feature, 다현, size/m

#46 [Feat/#36] Carousel 기본 구조 구현
  package.json
  src/assets/images/mainImgHotwriteLong.png
  src/assets/svgs/mainBtnBefore.svg
  src/assets/svgs/mainBtnBeforeHover.svg
  src/assets/svgs/mainBtnNext.svg
  src/assets/svgs/mainBtnNextHover.svg
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/style/slick-theme.css
  src/pages/main/style/slick.css
  src/styles/emotion.d.ts
  src/styles/theme.ts
  yarn.lock
Labels: ✨ Feature, 💄 Design, 다은, size/m

#49 [Feat/#43] 그룹페이지 뷰 구현 캐러셀 전까지
  src/assets/images/commonSystemthumImg.png
  src/assets/images/commonThumbnail.png
  src/assets/images/image_area.png
  src/assets/svgs/groupBestProfileIcnOpen.svg
  src/assets/svgs/groupDateIcn.svg
  src/assets/svgs/groupLeaderIcn.svg
  src/assets/svgs/groupListProfileIcnOpen.svg
  src/assets/svgs/groupMemberIcn.svg
  src/assets/svgs/index.tsx
  src/components/commons/Footer.tsx
  src/pages/groupFeed/CuriousArticle.tsx
  src/pages/groupFeed/CuriousProfile.tsx
  src/pages/groupFeed/GroupCuriousTitle.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/GroupInfoBox.tsx
  src/pages/groupFeed/GroupSideHeader.tsx
  src/pages/groupFeed/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/constants/CURIOUS_PROFILE.tsx
Labels: ✨ Feature, 다현, size/m

#50 [Feat/#44] 모임 페이지 캐러셀
  package.json
  src/assets/svgs/groupTabBeforeBtnEnable.svg
  src/assets/svgs/groupTabBeforeBtnHover.svg
  src/assets/svgs/groupTabBtnBaseBefore.svg
  src/assets/svgs/groupTabBtnBaseNext.svg
  src/assets/svgs/groupTabNextBtnEnable.svg
  src/assets/svgs/groupTabNextBtnHover.svg
  src/assets/svgs/index.tsx
  src/components/commons/Footer.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/CarouselContainer.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/carousel/slick-theme.css
  src/pages/groupFeed/carousel/slick.css
  src/pages/groupFeed/constants/CAROUSEL_DATA.tsx
Labels: ✨ Feature, 다현, size/l

#54 [fix/#53] svgConvention 맞추기
  src/assets/svgs/index.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/pages/groupFeed/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
Labels: 💄 Design, 다현, size/s

#51 [Feat/#47] Main 페이지 캐러셀 구현
  package.json
  src/assets/images/mainImgHotwriteShort.png
  src/assets/svgs/index.tsx
  src/assets/svgs/mainGroupRoutingBtn.svg
  src/assets/svgs/mainGroupRoutingBtnHover.svg
  src/assets/svgs/mainIcnArrowPurple.svg
  src/components/commons/Footer.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/Curious.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/Summary.tsx
  src/pages/main/constants/constants.ts
Labels: ✨ Feature, 다은, size/m

#57 [Feat/#52] 줄자 막대와 작미 소개
  src/assets/svgs/index.tsx
  src/assets/svgs/mainGraphicGradation.svg
  src/assets/svgs/mainGraphicLogo.svg
  src/assets/svgs/mainIcnArrowWhite.svg
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/Ruler.tsx
  src/pages/main/constants/keyword.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 다은, size/m

#62 [Feat/#58] 메뉴얼
  src/App.tsx
  src/pages/main/components/Manual.tsx
Labels: ✨ Feature, 다은, size/s

#56 [Feat/#48] post detail view
  src/App.tsx
  src/assets/images/defaultSeaImage.png
  src/assets/svgs/defaultProfileIc.svg
  src/assets/svgs/detailCommentMeatBallIc.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/postDetailCheckIc.svg
  src/assets/svgs/questionDefaultIc.svg
  src/assets/svgs/questionHoverIc.svg
  src/components/commons/Header.tsx
  src/pages/login/Login.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/constants/commentData.ts
  src/styles/GlobalStyle.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 재훈, size/l

#59 [Feat/#55] 그룹페이지 뷰 합치기 + 남은 뷰 구현
  src/Router.tsx
  src/assets/svgs/groupBestProfileSvg.svg
  src/assets/svgs/groupFloatingBtn.svg
  src/assets/svgs/groupFloatingBtnHover.svg
  src/assets/svgs/groupListProfileSvg.svg
  src/assets/svgs/groupNoDataImg.svg
  src/assets/svgs/index.tsx
  src/pages/groupFeed/CuriousArticle.tsx
  src/pages/groupFeed/CuriousProfile.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/GroupSideHeader.tsx
  src/pages/groupFeed/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/constants/CURIOUS_PROFILE.tsx
Labels: ✨ Feature, 다현, size/m

#61 [Feat/#32] 에디터 커스텀
  package.json
  src/Router.tsx
  src/assets/svgs/editorBoldSvgActive.svg
  src/assets/svgs/editorBoldSvgHover.svg
  src/assets/svgs/editorBoldSvgc.svg
  src/assets/svgs/editorBulletSvgActive.svg
  src/assets/svgs/editorBulletSvgEnable.svg
  src/assets/svgs/editorBulletSvgHover.svg
  src/assets/svgs/editorCenterSvgActive.svg
  src/assets/svgs/editorCenterSvgEnable.svg
  src/assets/svgs/editorCenterSvgHover.svg
  src/assets/svgs/editorDropIcnClose.svg
  src/assets/svgs/editorDropIcnOpen.svg
  src/assets/svgs/editorHorizonIcnUnactive.svg
  src/assets/svgs/editorHorizonSvgActive.svg
  src/assets/svgs/editorHorizonSvgEnable.svg
  src/assets/svgs/editorHorizonSvgHover.svg
  src/assets/svgs/editorItalicSvgActive.svg
  src/assets/svgs/editorItalicSvgEnable.svg
  src/assets/svgs/editorItalicSvgHover.svg
  src/assets/svgs/editorLeftSvgActive.svg
  src/assets/svgs/editorLeftSvgEnable.svg
  src/assets/svgs/editorLeftSvgHover.svg
  src/assets/svgs/editorLineSvgActive.svg
  src/assets/svgs/editorLineSvgEnable.svg
  src/assets/svgs/editorLineSvgHover.svg
  src/assets/svgs/editorNumberSvgActive.svg
  src/assets/svgs/editorNumberSvgEnable.svg
  src/assets/svgs/editorNumberSvgHover.svg
  src/assets/svgs/editorQuoteSvgActive.svg
  src/assets/svgs/editorQuoteSvgEnable.svg
  src/assets/svgs/editorQuoteSvgHover.svg
  src/assets/svgs/editorStrikeSvgActive.svg
  src/assets/svgs/editorStrikeSvgEnable.svg
  src/assets/svgs/editorStrikeSvgHover.svg
  src/assets/svgs/editorTextbasecolorIcnBlue.svg
  src/assets/svgs/editorTextbasecolorIcnGray.svg
  src/assets/svgs/editorTextbasecolorIcnGreen.svg
  src/assets/svgs/editorTextbasecolorIcnOrange.svg
  src/assets/svgs/editorTextbasecolorIcnPink.svg
  src/assets/svgs/editorTextbasecolorIcnRed.svg
  src/assets/svgs/editorTextbasecolorIcnViolet.svg
  src/assets/svgs/editorTextbasecolorIcnWhite.svg
  src/assets/svgs/editorTextbasecolorIcnYellow.svg
  src/assets/svgs/editorTextcolorIcnBlack.svg
  src/assets/svgs/editorTextcolorIcnBlue.svg
  src/assets/svgs/editorTextcolorIcnGray.svg
  src/assets/svgs/editorTextcolorIcnGreen.svg
  src/assets/svgs/editorTextcolorIcnOrange.svg
  src/assets/svgs/editorTextcolorIcnPink.svg
  src/assets/svgs/editorTextcolorIcnRed.svg
  src/assets/svgs/editorTextcolorIcnViolet.svg
  src/assets/svgs/editorTextcolorIcnYellow.svg
  src/assets/svgs/index.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/EditorToolBar.tsx
  src/pages/postPage/components/editor.css
  yarn.lock
Labels: ✨ Feature, 서진, size/xl

#69 [Feat/#60] kakao api
  package.json
  src/App.tsx
  src/assets/svgs/index.tsx
  src/components/commons/Footer.tsx
  src/pages/login/Login.tsx
  src/pages/login/RedirectLogin.tsx
  src/pages/login/queries/loginService.ts
  src/pages/login/types/loginType.ts
  src/pages/postDetail/components/CommentItem.tsx
  src/utils/apis/axios.ts
  src/utils/apis/login.ts
  yarn.lock
Labels: ✨ Feature, 재훈, size/m

#75 [Feat/#72] 에디터 뷰 제목 필드 추가
  src/Router.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/editor.css
Labels: ✨ Feature, 서진, size/m

#66 [Feat/#63] 캐러셀, 줄자, 작미소개, 메뉴얼 컴포넌트 합치기
  src/components/commons/Footer.tsx
  src/pages/main/Main.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/CuriousGroup.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/Manual.tsx
  src/pages/main/components/Summary.tsx
  src/pages/main/constants/constants.ts
Labels: ✨ Feature, 다은, size/m

#71 [Feat/#64] FAQ 드롭다운 구현
  src/assets/svgs/index.tsx
  src/assets/svgs/mainTogglearrowClosedIc.svg
  src/assets/svgs/mainTogglearrowOpenedIc.svg
  src/components/commons/Footer.tsx
  src/pages/main/Main.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/FaqTitle.tsx
  src/pages/main/components/GroupCarouselTitle.tsx
  src/pages/main/constants/constants.ts
  src/pages/main/constants/faqData.ts
Labels: ✨ Feature, 다은, size/m

#73 [Feat/#35] onBoarding 헤더 구현
  src/assets/svgs/index.tsx
  src/assets/svgs/mainIcnOnboarding.svg
  src/pages/main/Main.tsx
  src/pages/main/components/OnBoarding.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 다은, size/s

#70 [Feat/#67] 모임에 대한 권한 확인 API GET 연결
  package.json
  src/App.tsx
  src/assets/svgs/index.tsx
  src/components/commons/Header.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/CuriousProfile.tsx
  src/pages/groupFeed/components/GroupCuriousTitle.tsx
  src/pages/groupFeed/components/GroupInfoBox.tsx
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/components/MakeGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupBtn.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/PostDetail.tsx
  src/utils/apis/axios.ts
  yarn.lock
Labels: ✨ Feature, 다현, size/m

#78 [Feat/#77] 헤더 추가 + Main 뷰 컴포넌트 합치기
  src/assets/svgs/index.tsx
  src/assets/svgs/mainManualCurious.svg
  src/assets/svgs/mainManualJoin.svg
  src/assets/svgs/mainManualLook.svg
  src/assets/svgs/mainManualMake.svg
  src/assets/svgs/mainManualShare.svg
  src/assets/svgs/mainManualWrite.svg
  src/assets/svgs/mainOnBoarding.svg
  src/pages/main/Main.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/FaqTitle.tsx
  src/pages/main/components/GroupTitle.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/main/components/Manual.tsx
  src/pages/main/components/OnBoarding.tsx
  src/pages/main/style/slick-theme.css
Labels: ✨ Feature, 다은, size/m

#87 [ Feat/#82 ] 글모임 정보 받아오기 API GET
  src/assets/svgs/groupThumnailImg.svg
  src/assets/svgs/index.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/slick-theme.css
  src/pages/groupFeed/carousel/slick.css
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/main/components/MainHeader.tsx
Labels: ✨ Feature, 다현, size/m

#85 [Feat/#79] 캐러셀 API GET
  src/assets/svgs/mainOnBoarding.svg
  src/pages/main/Main.tsx
  src/pages/main/apis/getGroupContent.ts
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/GroupCarouselTitle.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/GroupTitle.tsx
  src/pages/main/components/Ruler.tsx
  src/pages/main/constants/constants.ts
  src/pages/main/types/moimPost.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 다은, size/m

#86 [Feat/#76] 글감, 필명 드롭다운 퍼블리싱
  src/assets/svgs/editorDropIcnActive.svg
  src/assets/svgs/editorDropIcnActiveopen.svg
  src/assets/svgs/index.tsx
  src/hooks/useClickOutside.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/Topic.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/constants/topicConstants.ts
  src/pages/postPage/types/topicType.ts
Labels: ✨ Feature, 서진, size/m

#89 [Feat/#83] 오늘의 글감 API GET
  package.json
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/CarouselContainer.tsx
  src/pages/groupFeed/components/GroupInfoBox.tsx
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/main/Main.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/main/style/slick-theme.css
  yarn.lock
Labels: ✨ Feature, 다현, size/l

#93 [Feat/#84] postDetail view - get api 연결
  src/App.tsx
  src/Router.tsx
  src/pages/Error/Error.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchCuriousInfo.ts
  src/pages/postDetail/apis/fetchPostDetail.ts
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
  src/pages/postDetail/hooks/useFetchPostDetail.ts
  src/pages/postPage/components/EditorToolBar.tsx
  src/utils/apis/axios.ts
  src/utils/logout.ts
Labels: ✨ Feature, 재훈, size/m

#94 [Feat/#92] 에디터 뷰 헤더 퍼블리싱
  src/components/commons/Header.tsx
  src/pages/postEditor/PostEditor.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/editor.css
  src/pages/postPage/constants/temporarySaveData.ts
Labels: ✨ Feature, 서진, size/m

#98 [ fix/#97] slick 화살표 에러
  src/assets/svgs/index.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/main/style/slick-theme.css
Labels: ⚒️ Fix, 다현, size/s

#100 [Feat/#84] post detail post api
  .eslintrc.json
  src/assets/svgs/detailPurplefavorite.svg
  src/assets/svgs/detailWhitefavorite.svg
  src/assets/svgs/index.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchCuriousInfo.ts
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
  src/pages/postPage/PostPage.tsx
Labels: ✨ Feature, 재훈, size/s

#104 [Feat/#99] 궁금해요 TOP 2 작가 API GET
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/components/CuriousProfile.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/groupFeed/hooks/queries.ts
Labels: ✨ Feature, 다현, size/m

#101 [Feat/#91] 캐러셀 라우팅 및 자잘한 변경
  src/assets/svgs/mainManualLook.svg
  src/pages/main/apis/getGroupContent.ts
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/CuriousGroup.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/main/components/Ruler.tsx
  src/pages/main/constants/introductionData.ts
  src/pages/main/types/moimPost.ts
Labels: ✨ Feature, ⚒️ Fix, 다은, size/m

#106 [ Feat/#105 ] 글모임별 글감 카테고리 API GET
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/main/style/slick.css
Labels: ✨ Feature, 다현, size/s

#109 [ Feat/#107 ] 궁금해요 TOP 2 글 API GET
  src/assets/svgs/groupCardThumnailImg.svg
  src/assets/svgs/index.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/hooks/queries.ts
Labels: ✨ Feature, 다현, size/m

#110 [Feat/#95] 에디터 이미지 업로드 구현 및 에디터 뷰 퍼블리싱 합치기
  src/assets/svgs/editorBoldSvgActive.svg
  src/assets/svgs/editorBoldSvgActivehover.svg
  src/assets/svgs/editorBoldSvgEnable.svg
  src/assets/svgs/editorBoldSvgHover.svg
  src/assets/svgs/editorBoldSvgc.svg
  src/assets/svgs/editorBulletSvgActive.svg
  src/assets/svgs/editorBulletSvgActivehover.svg
  src/assets/svgs/editorBulletSvgEnable.svg
  src/assets/svgs/editorBulletSvgHover.svg
  src/assets/svgs/editorCenterSvgActive.svg
  src/assets/svgs/editorCenterSvgActivehover.svg
  src/assets/svgs/editorCenterSvgEnable.svg
  src/assets/svgs/editorCenterSvgHover.svg
  src/assets/svgs/editorHorizonIcnUnactive.svg
  src/assets/svgs/editorHorizonSvgActive.svg
  src/assets/svgs/editorHorizonSvgActivehover.svg
  src/assets/svgs/editorHorizonSvgEnable.svg
  src/assets/svgs/editorHorizonSvgHover.svg
  src/assets/svgs/editorItalicSvgActive.svg
  src/assets/svgs/editorItalicSvgActivehover.svg
  src/assets/svgs/editorItalicSvgEnable.svg
  src/assets/svgs/editorItalicSvgHover.svg
  src/assets/svgs/editorLeftSvgActive.svg
  src/assets/svgs/editorLeftSvgActivehover.svg
  src/assets/svgs/editorLeftSvgEnable.svg
  src/assets/svgs/editorLeftSvgHover.svg
  src/assets/svgs/editorLineSvgActive.svg
  src/assets/svgs/editorLineSvgActivehover.svg
  src/assets/svgs/editorLineSvgEnable.svg
  src/assets/svgs/editorLineSvgHover.svg
  src/assets/svgs/editorNumberSvgActive.svg
  src/assets/svgs/editorNumberSvgActivehover.svg
  src/assets/svgs/editorNumberSvgEnable.svg
  src/assets/svgs/editorNumberSvgHover.svg
  src/assets/svgs/editorQuoteSvgActive.svg
  src/assets/svgs/editorQuoteSvgActivehover.svg
  src/assets/svgs/editorQuoteSvgEnable.svg
  src/assets/svgs/editorQuoteSvgHover.svg
  src/assets/svgs/editorStrikeSvgActive.svg
  src/assets/svgs/editorStrikeSvgActivehover.svg
  src/assets/svgs/editorStrikeSvgEnable.svg
  src/assets/svgs/editorStrikeSvgHover.svg
  src/assets/svgs/editorThuminputIcnActive.svg
  src/assets/svgs/editorThuminputIcnHover.svg
  src/assets/svgs/editorThuminputIcnUnactive.svg
  src/assets/svgs/index.tsx
  src/components/commons/Header.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/editor.css
Labels: ✨ Feature, 서진, size/l

#115 [ Fix/#114 ] merge error
  src/assets/svgs/index.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/CarouselContainer.tsx
  src/pages/groupFeed/components/GroupInfoBox.tsx
  src/pages/groupFeed/components/MakeGroupBtn.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/main/components/Carousel.tsx
Labels: ⚒️ Fix, 다현, size/s

#123 [ Feat/#111 ] 글감별 글 리스트 API GET
  src/components/commons/LogInOutBtn.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/apis/fetchGroupFeed.ts
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/hooks/queries.ts
Labels: ✨ Feature, 다현, size/m

#125 [Feat/#102] curious api 생성, 삭제구현
  src/assets/svgs/index.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/createPostCurious.ts
  src/pages/postDetail/apis/deleteCurious.ts
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ✨ Feature, 재훈, size/s

#116 [Feat/#108] 캐러셀 슬라이드 라우팅
  src/pages/main/ types/recommendTopic.ts
  src/pages/main/Main.tsx
  src/pages/main/apis/getGroupContent.ts
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/FaqTitle.tsx
  src/pages/main/components/GroupCarouselTitle.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/GroupNameButton.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/OnBoarding.tsx
  src/pages/main/styles/slick-theme.css
  src/pages/main/styles/slick.css
Labels: ✨ Feature, 다은, size/m

#118 [Fix/#117] login 페이지 svg 변경
  src/assets/svgs/index.tsx
  src/assets/svgs/kakaoLoginBtn.svg
  src/assets/svgs/loginIc.svg
  src/pages/login/Login.tsx
Labels: ⚒️ Fix, 다은, size/s

#129 [ Feat/#121 ] 글감 GET api 연결
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/fetchEditorContent.tsx
  src/pages/postPage/apis/postContent.tsx
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/Topic.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/hooks/queries.ts
Labels: ✨ Feature, 서진, size/m

#135 [ Feat/#124 ] 글에 해당하는 댓글 리스트 조회 API GET
  src/assets/svgs/index.tsx
  src/assets/svgs/textComentprofileSvg.svg
  src/pages/login/RedirectLogin.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchCommentList.ts
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ✨ Feature, 다현, size/m

#137 [Feat/#133] 로그인 로그아웃 라우팅
  src/pages/main/Main.tsx
  src/pages/main/components/CarouselSkeleton.tsx
  src/pages/main/components/MainHeader.tsx
Labels: ✨ Feature, 다은, size/s

#144 [Fix/#139] 캐러셀 이미지 수정
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/GroupContent.tsx
Labels: ⚒️ Fix, 다은, size/s

#141 [Feat/#132] 글 모임 버튼 라우팅
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/groupFeed/components/MyGroupBtn.tsx
  src/pages/main/components/CarouselSkeleton.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/Ruler.tsx
Labels: ✨ Feature, 다은, size/m

#142 [ Feat/#134 ] 댓글 생성 API POST
  src/pages/postDetail/apis/fetchPostComment.ts
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ✨ Feature, 다현, size/s

#143 [Feat/#128] post delete api
  src/pages/login/RedirectLogin.tsx
  src/pages/main/Main.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/styles/slick.css
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/deletePost.ts
  src/pages/postDetail/hooks/queries.ts
  src/pages/postPage/PostPage.tsx
Labels: ✨ Feature, 재훈, size/s

#145 [ feat/#131 ] 글 작성 POST api 연결
  src/pages/postEditor/PostEditor.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/createPostContent.tsx
  src/pages/postPage/apis/fetchPresignedUrl.tsx
  src/pages/postPage/apis/fetchTempSaveFlag.tsx
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/hooks/queries.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 서진, size/m

#156 merge
  src/pages/login/Login.tsx
Labels: size/xs

#164 [ Feat/146 ] 수정한 글 받아오기 GET, 수정하기 PUT api 연결
  src/Router.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postEditor/PostEditor.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/createPostContent.ts
  src/pages/postPage/apis/editPutContent.ts
  src/pages/postPage/apis/fetchEditContent.ts
  src/pages/postPage/apis/fetchEditorContent.ts
  src/pages/postPage/apis/fetchPresignedUrl.ts
  src/pages/postPage/apis/fetchTempSaveFlag.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/Topic.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/hooks/queries.ts
Labels: ✨ Feature, 서진, size/m

#169 Feat/#152/presigned url요청하기
  src/pages/login/Login.tsx
  src/pages/login/apis/loginService.ts
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/postDirectlyS3.ts
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/utils/s3UrlPasing.ts
Labels: ✨ Feature, 재훈, size/s

#151 feat: dangerouslySetInnerHTML 적용
  src/pages/postDetail/PostDetail.tsx
Labels: ✨ Feature, 재훈, size/xs

#147 [Fix/#138] 로그아웃 리로드
  src/pages/main/Main.tsx
  src/pages/main/components/MainHeader.tsx
Labels: ⚒️ Fix, 다은, size/xs

#154 [ Feat/#136 ] 댓글 삭제 API DELETE
  src/assets/svgs/editorCatSvg.svg
  src/assets/svgs/index.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/carousel/slick-theme.css
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/components/MakeGroupBtn.tsx
  src/pages/postDetail/apis/fetchDeleteComment.ts
  src/pages/postDetail/apis/fetchPostComment.ts
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/hooks/queries.ts
  src/pages/postDetail/hooks/useFetchPostDetail.ts
Labels: ✨ Feature, 다현, size/m

#158 [Fix/#157] svg 절대경로
  src/pages/main/styles/slick-theme.css
Labels: 🐛 Bug, 다은, size/s

#160 [ fix/#159 ] topicId 없을때는 요청 안쏘게
  src/pages/groupFeed/hooks/queries.ts
Labels: ⚒️ Fix, 다현, size/xs

#163 [Feat/#162] favicon 세팅
  index.html
  src/assets/svgs/faviconMile.svg
  src/assets/svgs/index.tsx
Labels: ✨ Feature, 다은, size/s

#150 [Fix/#148] 라우팅 추가 및 수정
  src/pages/main/components/CuriousGroup.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/Introduction.tsx
Labels: ⚒️ Fix, 다은, size/s

#183 [Feat/#172] temp store post get (급한 QA먼저 수정한 브랜치입니다. )
  src/components/commons/Header.tsx
  src/hooks/useNavigateHome.ts
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/login/Login.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/fetchTempSaveContent.ts
  src/pages/postPage/apis/postDirectlyS3.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/editor.css
  src/pages/postPage/hooks/queries.ts
  src/utils/logout.ts
Labels: ✨ Feature, 재훈, size/m

#168 [Feat/#122] 스켈레톤 UI
  src/pages/main/Main.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/CarouselPage.tsx
  src/pages/main/components/CarouselSkeleton.tsx
  src/pages/main/components/CarouselSkeletonPage.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/Skeleton.tsx
  src/pages/main/styles/slick-theme.css
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 다은, size/m

#176 [Fix/#175] image rendering
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentItem.tsx
Labels: ⚒️ Fix, 다현, size/s

#180 [fix/#179] Header svg 변경
  src/assets/svgs/headerLogoSvg.svg
Labels: 💄 Design, 다은, size/s

#181 [Feat/#161] 에러페이지 제작
  src/assets/svgs/errorIc.svg
  src/assets/svgs/index.tsx
  src/pages/Error/Error.tsx
Labels: ✨ Feature, 다은, size/s

#184 [ Fix/#182 ]error handling 403
  src/pages/postDetail/apis/fetchCommentList.ts
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ⚒️ Fix, 다현, size/s

#185 develop to main merge
  README.md
  index.html
  src/assets/gifs/loadingSpinner.gif
  src/assets/svgs/errorIc.svg
  src/assets/svgs/headerLogoSvg.svg
  src/assets/svgs/index.tsx
  src/components/commons/Header.tsx
  src/hooks/useNavigateHome.ts
  src/pages/Error/Error.tsx
  src/pages/Loading/Loading.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/groupFeed/hooks/queries.ts
  src/pages/login/Login.tsx
  src/pages/login/RedirectLogin.tsx
  src/pages/main/Main.tsx
  src/pages/main/components/Carousel.tsx
  src/pages/main/components/CarouselPage.tsx
  src/pages/main/components/CarouselSkeleton.tsx
  src/pages/main/components/CarouselSkeletonPage.tsx
  src/pages/main/components/CuriousGroup.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/components/GroupContent.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/main/components/Skeleton.tsx
  src/pages/main/styles/slick-theme.css
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchCommentList.ts
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/fetchTempSaveContent.ts
  src/pages/postPage/apis/postDirectlyS3.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/editor.css
  src/pages/postPage/hooks/queries.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/utils/logout.ts
Labels: size/l

#186 [Feat/#167] editor temp save get
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/login/Login.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/saveTempSaveContent.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/hooks/queries.ts
Labels: size/m

#187 main merge !!!!!
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/login/Login.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/saveTempSaveContent.ts
  src/pages/postPage/components/DropDown.tsx
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/WriterDropDown.tsx
  src/pages/postPage/hooks/queries.ts
Labels: size/m

#194 [ Fix/#190 ] 궁금해요 403 에러 handling
  src/pages/postDetail/apis/fetchCuriousInfo.ts
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ⚒️ Fix, 다현, size/s

#195 [ fix/#192 ] main arrow css 모임 arrow 안 덮게
  src/pages/main/styles/slick-theme.css
Labels: ⚒️ Fix, 다현, size/xs

#197 [ Feat/#196 ] 로딩스피너 적용 및 에러페이지 라우팅 수정
  src/pages/Error/Error.tsx
  src/pages/Loading/Loading.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/postDetail/PostDetail.tsx
Labels: ✨ Feature, ⚒️ Fix, 다현, size/s

#198 main merge
  src/pages/Error/Error.tsx
  src/pages/Loading/Loading.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
  src/pages/main/components/FaqDropdown.tsx
  src/pages/main/styles/slick-theme.css
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/apis/fetchCuriousInfo.ts
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postDetail/hooks/queries.ts
Labels: ⚒️ Fix, 다현, size/s

#200 Fix/#193/qafix change post
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/postDirectlyS3.ts
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/ImageUpload.tsx
Labels: size/s

#201 [ Fix/#199 ] 모임페이지 qa
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postPage/PostPage.tsx
Labels: ⚒️ Fix, 다현, size/s

#204 [Fix/#203] header routing
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/apis/editPutContent.ts
  src/pages/postPage/components/editor.css
Labels: ⚒️ Fix, 다현, size/s

#205 merge Develop to Merge
  src/pages/groupFeed/carousel/Carousel.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/GroupFeedHeader.tsx
  src/pages/main/components/MainHeader.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/pages/postPage/PostPage.tsx
  src/pages/postPage/apis/editPutContent.ts
  src/pages/postPage/apis/postDirectlyS3.ts
  src/pages/postPage/components/Editor.tsx
  src/pages/postPage/components/ImageUpload.tsx
  src/pages/postPage/components/editor.css
Labels: size/s

#207 fix/#203: 삭제에 커서
  src/pages/postDetail/components/CommentItem.tsx
Labels: ⚒️ Fix, 다현, size/xs

#208 Develop merge
  src/pages/postDetail/components/CommentItem.tsx
Labels: ⚒️ Fix, 다현, size/xs

#211 fix/#210 : qa
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/pages/postPage/PostPage.tsx
Labels: ⚒️ Fix, 다현, size/xs

#212 Develop to main
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/GroupSideHeader.tsx
  src/pages/postPage/PostPage.tsx
Labels: size/xs
