Repository Mile-Writings/Mile-Client, pull requests merged in 2025-04, with the labels that each got.

#555 [Fix/#554] 가입 가능한 글 모임 개수 수정
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/constants/count.ts
  src/pages/groupFeed/constants/modalContent.ts
  src/pages/main/constants/faqData.ts
Labels: ⚒️ Fix, 다은, size/s

#556 [Fix/#553] 이미지 비율 수정
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/components/ImageUpload.tsx
Labels: ⚒️ Fix, 다현, size/s

#557 글모임 개수 & 이미지 비율 수정 main merge
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/components/CreateGroupBtn.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
  src/pages/groupFeed/constants/count.ts
  src/pages/groupFeed/constants/modalContent.ts
  src/pages/main/constants/faqData.ts
  src/pages/postDetail/PostDetail.tsx
  src/pages/postPage/components/ImageUpload.tsx
Labels: size/m

#559 [HotFix] qa
  src/assets/svgs/index.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
Labels: size/xs

#560 main merge
  src/assets/svgs/index.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/MyGroupDropDown.tsx
Labels: size/xs
