Repository Mile-Writings/Mile-Client, pull requests merged in 2025-01, with the labels that each got.

#526 [Fix/#525] 글모임초대페이지 QA
  src/pages/groupInvite/components/UserInfoInput.tsx
  src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
Labels: ⚒️ Fix, 서진, size/s

#524 [Feat/#523] 관리자 페이지 QA 해결
  src/components/commons/Header.tsx
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/admin/components/MemberItem.tsx
  src/pages/admin/components/MemberManage.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/utils/PageNumber.tsx
Labels: ⚒️ Fix, 다은, size/s

#528 [Fix/#521] 모임페이지 QA
  src/pages/groupFeed/GroupFeed.tsx
  src/pages/groupFeed/carousel/EachArticle.tsx
  src/pages/groupFeed/components/CuriousArticle.tsx
  src/pages/groupFeed/components/CuriousProfile.tsx
  src/pages/groupFeed/components/EditProfileModal.tsx
  src/pages/groupFeed/components/GroupMobileInfo.tsx
Labels: ⚒️ Fix, 다현, size/m

#530 [ Fix/#527 ] Group create page / Group Info Edit page QA반영
  src/assets/svgs/groupImageRemove.svg
  src/assets/svgs/index.tsx
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/admin/constants/modal.ts
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupLeaderInfo.tsx
  src/pages/createGroupSuccess/CreateGroupSuccess.tsx
Labels: ⚒️ Fix, 재훈, size/m

#531 [feat/#521] 에러페이지 반응형
  src/pages/error/Error.tsx
Labels: ✨ Feature, 다현, size/s

#532 [ Fix/#522 ] 메인페이지 QA반영
  src/pages/main/Main.tsx
  src/pages/main/components/GroupCarousel.tsx
  src/pages/main/components/Introduction.tsx
  src/pages/main/components/Manual.tsx
Labels: ⚒️ Fix, 재훈, size/s

#536 [ Fix/#520 ] 에디터 페이지 QA 반영
  src/components/commons/Button.tsx
  src/pages/postPage/components/TipTap.tsx
  src/pages/postPage/components/TopicDropDown.tsx
  src/pages/postPage/components/tiptap.css
Labels: ⚒️ Fix, 서진, size/m

#537 [ Fix/#519 ] 글 상세페이지 QA 반영
  index.html
  package-lock.json
  src/pages/groupInvite/components/UserInfoInput.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/Comment.tsx
  src/pages/postDetail/components/CommentInputBox.tsx
  src/pages/postDetail/components/CommentItem.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
Labels: ⚒️ Fix, 서진, size/s

#538 [ Fix/#533 ] 궁금해요 줄바꿈 및 iOS 환경 대응 QA
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupInfo.tsx
  src/pages/createGroup/components/CreateGroupLeaderInfo.tsx
  src/pages/createGroupSuccess/CreateGroupSuccess.tsx
  src/pages/groupFeed/components/EditProfileModal.tsx
  src/pages/main/Main.tsx
  src/pages/postDetail/PostDetail.tsx
  src/pages/postDetail/components/CommentInputBox.tsx
  src/pages/postDetail/components/CuriousBtn.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ⚒️ Fix, 재훈, size/m

#539 [ Fix/#533 ] qa etc
  src/pages/admin/Admin.tsx
  src/pages/admin/components/EditGroupInfo.tsx
  src/pages/admin/components/RenderAdminContent.tsx
  src/pages/groupFeed/components/GroupInfoBox.tsx
  src/pages/groupFeed/components/GroupMobileInfo.tsx
  src/pages/main/components/GroupCarousel.tsx
Labels: ⚒️ Fix, 재훈, size/s

#541 [fix] 모임페이지 글자수 수정 및 글자 정렬 qa
  src/pages/groupFeed/components/GroupMobileInfo.tsx
  src/pages/groupFeed/components/GroupSideHeader.tsx
Labels: size/s

#544 [Feat] Google Analytics 세팅
  package.json
  src/App.tsx
  src/routers/RouteTracker.tsx
  yarn.lock
Labels: ✨ Feature, 다은, size/s

#545 [Fix/#543] RouteTracker 호출 위치 변경
  src/App.tsx
  src/components/commons/Layout.tsx
  src/routers/PrivateRoute.tsx
Labels: ⚒️ Fix, 다은, size/s

#546 [Merge] main merge
  package.json
  src/App.tsx
  src/components/commons/Layout.tsx
  src/routers/PrivateRoute.tsx
  src/routers/RouteTracker.tsx
  yarn.lock
Labels: size/s
